#!/bin/sh

dmenufont='Hack-14'
dmenunb='#1c2023'
dmenunf='#f3f4f5'
dmenusb='#c795ae'
dmenusf='#1c2023'
surfun='#c7ae95'

# [ -z $1 ] && printf "empty input\n" && exit 1

chosen=$(printf "Firefox\nPrivate\nSurf" | dmenu -i -p "Browser" -fn $dmenufont -nb $dmenunb -nf $dmenunf -sb $dmenusb -sf $dmenusf)

if [ -z $1 ]
then
	case $chosen in
		Firefox) firefox;;
		Private) firefox --private-window "https://duckduckgo.com";;
		Surf) tabbed -t $dmenunb -T $dmenusb -u $dmenunb -U $surfun -cr 2 surf -pe x "https://duckduckgo.com";;
		*) notify-send "dmenu-browser" "Could not resolve browser string";;
	esac
else
	case $chosen in
		Firefox) firefox "$1";;
		Private) firefox --private-window "$1";;
		Surf) tabbed -t $dmenunb -T $dmenusb -u $dmenunb -U $surfun -cr 2 surf -pe x "$1";;
		*) $BROWSER "$1";;
	esac
fi
