#!/bin/bash

dmenufont='Hack-9'
dmenunb='#1c2023'
dmenunf='#f3f4f5'
dmenusb='#aec795'
dmenusf='#1c2023'

input=

while read stdin

	do input="$input$stdin\n"

done

chosen="$(printf "$input" | extracturls | dmenu -i -p "URL:" -l 10 -fn $dmenufont -nb $dmenunb -nf $dmenunf -sb $dmenusb -sf $dmenusf)"

urlhandler $chosen
