#!/bin/sh

dmenufont='Hack-9'
dmenunb='#1c2023'
dmenunf='#f3f4f5'
dmenusb='#aec795'
dmenusf='#1c2023'

# [ -z $1 ] && printf "empty input\n" && exit 1

chosen=$(printf "Firefox\nPrivate\nSurf" | dmenu -i -p "Browser" -fn $dmenufont -nb $dmenunb -nf $dmenunf -sb $dmenusb -sf $dmenusf)

if [ -z $1 ]
then
	case $chosen in
		Firefox) firefox;;
		Private) firefox --private-window "https://duckduckgo.com";;
		Surf) tabbed -t '#1c2023' -T '#c795ae' -u '#1c2023' -U '#c7ae95' -cr 2 surf -pe x "https://duckduckgo.com";;
		*) $BROWSER;;
	esac
else
	case $chosen in
		Firefox) firefox "$1";;
		Private) firefox --private-window "$1";;
		Surf) tabbed -t '#1c2023' -T '#c795ae' -u '#1c2023' -U '#c7ae95' -cr 2 surf -pe x "$1";;
		*) $BROWSER "$1";;
	esac
fi
