#!/bin/bash

dmenufont='Hack-14'
dmenunb='#1c2023'
dmenunf='#f3f4f5'
dmenusb='#ae95c7'
dmenusf='#1c2023'

wireguard-up () { \
	vpn=$(ls /etc/wireguard/ 2>/dev/null | sed 's/\.conf//g' | dmenu -i -p 'VPN:' -fn $dmenufont -nb $dmenunb -nf $dmenunf -sb $dmenusb -sf $dmenusf)

	valid=$(ls /etc/wireguard/ 2>/dev/null | grep $vpn)

	[ -z "$vpn" ] && notify-send "dmenu-wireguard" "No VPN chosen" && exit 1

	[ -z "$valid" ] && notify-send -u critical "dmenu-wireguard" "Invalid VPN chosen" && exit 1

	sudo -A wg-quick up $vpn && notify-send -u low "dmenu-wireguard" " Connected to $vpn"
}

wireguard-down () { \
	vpn=$(wg show interfaces | dmenu -i -p 'VPN:' -fn $dmenufont -nb $dmenunb -nf $dmenunf -sb $dmenusb -sf $dmenusf)

	valid=$(wg show interfaces | grep $vpn)

	[ -z "$vpn" ] && notify-send "dmenu-wireguard" "No VPN chosen" && exit 1

	[ -z "$valid" ] && notify-send -u critical "dmenu-wireguard" "Invalid VPN Chosen" && exit 1

	sudo -A wg-quick down $vpn && notify-send -u low "dmenu-wireguard" "Disconnected from $vpn"
}

chosen=$(echo -e 'Up\nDown' | dmenu -i -p 'Type to Manage:' -fn $dmenufont -nb $dmenunb -nf $dmenunf -sb $dmenusb -sf $dmenusf)

case $chosen in
	Up) wireguard-up;;
	Down) wireguard-down;;
	*) notify-send "dmenu-wireguard" "Could not resolve management string for WireGuard"
esac
