#!/bin/bash

dmenufont='Hack-9'
dmenunb='#1c2023'
dmenunf='#f3f4f5'
dmenusb='#aec795'
dmenusf='#1c2023'

input=

while read stdin

	do input="$input$stdin\n"

done

chosen="$(printf "$input" | grep -oE "(https?://|ftp://|www.)[A-Za-z0-9.~'*,()_/:;$\?\#@%&!=-\+]+|mailto:[a-zA-Z0-9._-]*@[a-zA-Z0-9._-]*" | dmenu -i -p "URL:" -l 10 -fn $dmenufont -nb $dmenunb -nf $dmenunf -sb $dmenusb -sf $dmenusf)"

[ -z "$chosen" ] exit

urlhandler $chosen
