#!/bin/bash

dmenufont='Hack-9'
dmenunb='#1c2023'
dmenunf='#f3f4f5'
dmenusb='#c795ae'
dmenusf='#1c2023'

if [ -z "replace this string with a empty one to use dmenu instead of read to take the credentials" ]
then

	githubuser=$(dmenu -p "Username for 'https://gist.github.com':" -fn $dmenufont -nb $dmenunb -nf $dmenunf -sb $dmenusb -sf $dmenusf <&-)
	githubpass=$(dmenu -p "Password for 'https://gist.github.com/"$githubuser"':" -fn $dmenufont -nb $dmenunb -nf $dmenunb -sb $dmenusb -sf $dmenusf <&-)

else

	read -p "Username for 'https://gist.github.com': " githubuser
	read -s -p "Password for 'https://gist.github.com/"$githubuser"': " githubpass
	printf "\n"

fi

for FILE in "$@"
do
	# I have to pipe the sed commands seperately otherwise they don't work right. for some reason
	content=$(cat $FILE | sed -r 's/\\/\\\\/g' | sed -r ':a; N; $!ba; s/\n/\\n/g' | sed -r 's/\t/\\t/g' | sed -r 's/"/\\"/g')
	json=$json"\"$FILE\":{\"content\":\"$content\"},"
done

json=$(echo $json | sed -e 's/.$//g')

curl -X POST -d "{\"public\":true,\"files\":{$json}}" -u $githubuser:$githubpass https://api.github.com/gists
