#!/bin/sh

#landscape (normal)

xrandr -o normal
xinput set-prop "Atmel Atmel maXTouch Digitizer" --type=float "Coordinate Transformation Matrix" 0 0 0 0 0 0 0 0 0
#xinput set-prop "Your Touchpad's name, if applicable" --type=float "Coordinate Transformation Matrix" 0 0 0 0 0 0 0 0 0
#↳
xinput enable "SynPS/2 Synaptics TouchPad"
