#!/bin/sh

#landscape (inverted)

xrandr -o inverted
xinput set-prop "Atmel Atmel maXTouch Digitizer" --type=float "Coordinate Transformation Matrix" -1 0 1 0 -1 1 0 0 1
#xinput set-prop "Your Touchpad's name, if applicable" --type=float "Coordinate Transformation Matrix" -1 0 1 0 -1 1 0 0 1
xinput disable "SynPS/2 Synaptics TouchPad"
