#!/bin/sh

# This is made to play episodes of a series that have been marked in some numerical order. Best used with databases that are organized with similar naming scheme to:
# "[$SERIES_NAME].S[$SEASON]E[$EPISODE].[$SEASON_NAME].[$EPISODE_NAME]"
# "[$SERIES_NAME].S[$SEASON].[$SEASON_NAME].E[$EPISODE].[$EPISODE_NAME]"

episodes=$(ls -al | tail -n +3 | grep -iE 'mp4|mkv|avi|vob|webm|m4v' | grep -iA 1000 "$1" | awk -F' ' '{print $9}' | tr '\n' ' ')

mpv $episodes
