#!/bin/sh

walldir="/home/$(whoami)/Pictures/Wallpapers/Seasonal/$(get-season)/"
# walldir="/home/$(whoami)/Pictures/Wallpapers/Landscapes/"

wal=$(find $walldir | grep -iE 'jpg|jpeg|png' | shuf -n 1)

convert $wal ~/.wallpaper.png

set-wallpaper
