#!/bin/sh

# Pipe or give this script a url and it will dicern how to handle it.
# if the file is a image then it will be opened in sxiv
# if the file is a video it will be opened in mpv
# if the file is a pdf it will be downloaded
# else the file will open in the browser
#  -t '#1c2023' -T '#c795ae' -u '#1c2023' -U '#c7ae95'

BROWSE="tabbed -cr 2 surf -pe x"

ext="${1##*.}"
videoFiles="mkv mp4 gif avi"
imageFiles="png jpg jpeg jpe"
wgetFiles="pdf"
ytFiles="youtube.com|youtu.be"

if echo $videoFiles | grep -w $ext > /dev/null; then
	nohup mpv --loop --quiet "$1" > /dev/null &
elif echo $imageFiles | grep -w $ext > /dev/null; then
	nohup feh "$1" > /dev/null &
elif echo $wgetFiles | grep -w $ext > /dev/null; then
	nohup wget "$1" > /dev/null &
elif [ -z $(echo $1 | grep -ivE $ytFiles) ]; then
	# change me to youtubedl?
	nohup mpv --quiet "$1" > /dev/null &
else
	nohup $BROWSE "$1" > /dev/null &
fi
